### ISSUE TITLE
Feature Request: Draw Arrows on the Map

### ISSUE THREAD

**Issue by bachlge** [FlowingCode/GoogleMapsAddon#1]
Drawing Arrows on a map is described in the [Google Maps Documentation](https://developers.google.com/maps/documentation/javascript/symbols#arrows).
It makes use of Google Maps Symbols by adding them to the `icon`-property of the `Polyline`.
The javascript code in [google-map-poly.js](https://github.com/FlowingCode/google-map/blob/master/google-map-poly.js) already contains the `icons`-property, however I could not find this covered by the Java implementation [GoogleMapPolygon.java](https://github.com/FlowingCode/GoogleMapsAddon/blob/master/src/main/java/com/flowingcode/vaadin/addons/googlemaps/GoogleMapPolygon.java). 
I ask to consider this enhancement idea in a future version of the addon.
Thank you!

**Comment by mlopezFC** [comment]
Latest commit message was wrong, it's related to #4 ☝️
