### ISSUE TITLE
Screen Shot Feature

### ISSUE THREAD

**Issue by JariHanah** [FlowingCode/GoogleMapsAddon#131]
### Feature proposal

It would be great to populate the Map with Marks Polygons, etc... then either automatically allow the user, or backend to store a screenshot for easy share. I noticed this feature seems available in the Android Map Api, and static Google Image Map Api. 

****

### Describe solution expectations

I would think there is a Google JS Map Api to do this.

**Comment by paodb** [comment]
Hi @JariHanah we've been investigating but we're not able to find documentation regarding this feature. As you mentioned "_I noticed this feature seems available in the Android Map Api, and static Google Image Map Api_." can you share some links or information about it? Thanks

**Comment by paodb** [comment]
Closing this issue due to lack of response. Feel free to reopen if you can provide more details.
