### ISSUE TITLE
Internally manage trackLocationId

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/GoogleMapsAddon#133]
### Feature proposal

Enhance the location tracking functionality by refactoring `GoogleMap` to internally manage the `trackLocationId`. This will streamline the user experience.

The current implementation has a `stopTrackLocation(int)` method  requiring a `trackLocationId` parameter. This approach is redundant and can be simplified by refactoring the `GoogleMap` class to manage the `trackLocationId` internally. 

### Describe solution expectations

Refactor `GoogleMap` class: modify the `GoogleMap` class to internally store and manage the `trackLocationId`.

#### Implementation Details:

- Add a private member variable to store the trackLocationId.
- Modify the trackLocation() method to assign the trackLocationId.
- Remove the trackLocationId parameter from the stopTrackLocation method and use the stored trackLocationId.

```
public class GoogleMap {
    private int trackLocationId;

    public void trackLocation() {
        // Logic to start tracking and obtain the trackLocationId
        trackLocationId = ...; // Obtain and store the trackLocationId
    }

    public void stopTrackLocation() {
        // Logic to stop tracking using the stored trackLocationId
        if (trackLocationId != 0) {
            // Stop tracking logic using trackLocationId
        }
    }
}
```

#### Benefits:
- Simplified API: Users of the `GoogleMap` class no longer need to manage the `trackLocationId` externally, making the API simpler and more intuitive.

- Reduced Redundancy: Eliminates the redundancy and potential errors associated with external management of `trackLocationId`.

- Improved Maintainability: Internal management of `trackLocationId` improves the maintainability and readability of the `GoogleMap` class.
 
- Encapsulation: Keeps the tracking logic encapsulated within the  `GoogleMap` class, adhering to object-oriented design principles.

By implementing this enhancement, the gmaps class will provide a cleaner, more user-friendly API, reducing the potential for errors and improving the overall code quality.

**Comment by paodb** [comment]
Released in version [2.0.0](https://github.com/FlowingCode/GoogleMapsAddon/releases/tag/google-maps-2.0.0).
