### ISSUE TITLE
Map not shown in Vaadin 23

### ISSUE THREAD

**Issue by thiasos** [FlowingCode/GoogleMapsAddon#146]
### Describe the bug

Since today, I noticed that Map AddOn does not work anymore (check also you example). 
I've check with Chrome, FireFox and Edge: same result: java script error:
Uncaught (in promise) TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function
    at qwa (map.js:37:176)
    at Lxa.changed (map.js:107:360)
    at al (js?...

### Minimal reproducible example

Open Page with Map (also you can check your demo)

### Add-on Version

2.2.0

### Vaadin Version

23.3.32

**Comment by pawelpm** [comment]
Exactly the same problem with my app.

**Comment by kochstef** [comment]
Same problem with Vaadin 24.

**Comment by djimenezgarcia** [comment]
Same error!

We´ve seen this error today. Yesterday everything was working fine.

Any change in google´s online javascript libraries?

**Comment by jonasrotilli** [comment]
Exactly the same problem with my app.

**Comment by crontabpy** [comment]
same problem here.

**Comment by paodb** [comment]
The issue has to do with some ongoing changes on Google Maps regarding [styles](https://developers.google.com/maps/new-map-style-opt-in) that we haven't address yet. In order to get the add-on to work we need to pin the version of the javascript library in use in our [web-component]( https://github.com/FlowingCode/google-map/blob/82956da7d17eb85ef17bfa990aca427d5b595162/google-map.js#L296) as explained [here](https://developers.google.com/maps/new-map-style-opt-in#opt-out) .

Sorry for the inconveniencies, we'll let you know when a new release is done.

**Comment by djimenezgarcia** [comment]
Hi Paola. 

I do not see what changes needs to be done in your component to solve the problem. Is something to be done on code?. As shown in spanish: "Para la API de Maps JavaScript, puedes inhabilitar la versión más reciente utilizando la versión 3.57, independientemente de qué canal uses.".

How can i set maps version using your API?


Thanks in advance!

**Comment by paodb** [comment]
The version of the JavaScript library used in the component is given by the [version property in the web-component](https://github.com/FlowingCode/google-map/blob/82956da7d17eb85ef17bfa990aca427d5b595162/google-map.js#L294), as it has value "`3.exp`" is taken the latest available version of the Javascript library. We need to stick to 3.57 for now so we need to update that property value. There's no API in the add-on to do so (and I'm conflicted about if it should be a part of the API or not). 
But as a workaround you could use the element API to set the property like `googlemaps.getElement().setAttribute("version", "3.57");` after the constructor is being called.

**Comment by jonasrotilli** [comment]
> googlemaps.getElement().setAttribute("version", "3.57");

This will require a bit of work to modify in all the classes where we use it, but it will temporarily solve the problem!
Thank you very much!

**Comment by djimenezgarcia** [comment]
That´s right!. The change fix the problem!.


> > googlemaps.getElement().setAttribute("version", "3.57");
> 
> This will require a bit of work to modify in all the classes where we use it, but it will temporarily solve the problem! Thank you very much!

**Comment by paodb** [comment]
Please try new released version [2.2.1](https://vaadin.com/directory/component/google-maps-addon/2.2.1)

**Comment by pawelpm** [comment]
New released version [2.2.1](https://vaadin.com/directory/component/google-maps-addon/2.2.1) full solved problem in my app
