### ISSUE TITLE
Maps are not rendering

### ISSUE THREAD

**Issue by ziza** [FlowingCode/GoogleMapsAddon#148]
### Describe the bug

My project's maps stop rendering, it's also happening in the component demo.

https://addonsv24.flowingcode.com/googlemaps/googlemaps

![image](https://github.com/user-attachments/assets/424f7a5e-9f59-4c70-94f2-d4d53ff72f0e)

### Expected behavior

Display maps correctly

### Minimal reproducible example

Open the project demo
https://addonsv24.flowingcode.com/googlemaps/googlemaps

### Add-on Version

2.2.1

### Vaadin Version

24.5.7

**Comment by ziza** [comment]
Sorry, the problem is only in the demo which is still on v2.2.0, thanks.

**Comment by paodb** [comment]
@ziza sorry we missed that, we're updating it.
