### ISSUE TITLE
Add support for KML Layer

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/GoogleMapsAddon#23]
It would be good to add support for adding KML layers

**Comment by umitkirtil** [comment]
Hi , Any updates on this ?

**Comment by paodb** [comment]
I've been investigating this feature and an initial implementation can be done as the web-component already has support for sending an [kml url](https://github.com/FlowingCode/google-map/blob/2da0dd8aa919d4f2d47cd848527f6773b29be158/google-map.js#L224) to display a [kml layer on a map](https://github.com/FlowingCode/google-map/blob/2da0dd8aa919d4f2d47cd848527f6773b29be158/google-map.js#L669). Then we could add more functionality and options as explained [here](https://developers.google.com/maps/documentation/javascript/kmllayer#kml_layer_options), but the web-component part will need to be updated first.
