### ISSUE TITLE
Error when adding markers to map

### ISSUE THREAD

**Issue by ED-SD** [FlowingCode/GoogleMapsAddon#25]
Hello,

I integrated you very nice plugin to my Vaadin Application.

When I'm adding markers to the map, I get the attached error. The strange thing is, when I'm refresh the browser after getting the error it works.

Please let me know, If you need more informations.

Best regards,
Johannes
![bug](https://user-images.githubusercontent.com/50275136/108586525-6344dc80-734f-11eb-82b1-bf518a1a63d9.PNG)

**Comment by magnusahlden** [comment]
Any news? we had the exact same issue...

**Comment by ED-SD** [comment]
Hi magnusahlden,

I solved the problem by adding the markers after loading the page. A very ugly solutions, but it works.

`
		// Start Polling when attaching this component
		addAttachListener(attachEvent ->
		{
			if (pollListener.get()==null)
			{
				UI.getCurrent().setPollInterval(5000);

				Registration registration = UI.getCurrent().addPollListener(pollEvent -> {
// ADD OR UPDATE MARKERS HERE
				});

				pollListener.set(registration);
			}
		});

		// Stop Polling when detaching this component
		addDetachListener(detachEvent ->
		{
			if (pollListener.get()!=null)
			{
				UI.getCurrent().setPollInterval(-1);

				pollListener.get().remove();
				pollListener.set(null);
			}
		});
`

**Comment by paodb** [comment]
Hello @ED-SD, @magnusahlden. There's a new release of the component fixing this issue. Can you give it a try? Thanks.

**Comment by javier-godoy** [comment]
Should be fixed in v1.2.1. Feel free to reopen this issue if it's not the case.
