### ISSUE TITLE
Please add support for mapId

### ISSUE THREAD

**Issue by ijazfx** [FlowingCode/GoogleMapsAddon#58]
Google Maps allows us to style our maps with unique mapId. Once the style is defined, we can pass that to maps component. PFB link for details.

https://developers.google.com/maps/documentation/javascript/cloud-based-map-styling#maps_map_id_style-javascript

**Comment by paodb** [comment]
This depends on https://github.com/FlowingCode/google-map/issues/15 to be ready.

**Comment by paodb** [comment]
MapId support is now available in version 1.6.0.

**Comment by ijazfx** [comment]
Great!! let me check and confirm. Best regards
