### ISSUE TITLE
Map not rendering and error thrown in browser console

### ISSUE THREAD

**Issue by thomasdewaelheyns** [FlowingCode/GoogleMapsAddon#65]
When using the Google Maps Addon widget, the map is not shown and an exception is being thrown to the console of the browser.

The visualization in the browser:
![image](https://user-images.githubusercontent.com/1107343/154444305-ab6c6a62-16b6-4994-970c-9ee7c22b3609.png)

The following error is being shown in the console:
![image](https://user-images.githubusercontent.com/1107343/154444058-514c22bb-ff98-40f8-abf9-74a4f79f6139.png)

This problem also occurs on the online demo of the Vaadin addon at [https://addonsv14.flowingcode.com/googlemaps](https://addonsv14.flowingcode.com/googlemaps)

**Platform versions:**
Google Maps Addon version: 1.6.0
Vaadin version: 14.8.4

**Verified in:**
Chrome: 98.0.4758.82
Firefox: 97.0 (64-bit)

**Comment by javier-godoy** [comment]
@CodeMonkeyLab Thanks. Indeed, reverting to version 1.5.0 (that doesn't have the MapID feature) seems to avoid this issue. This is clearly a bug since MapID was intended as an optional feature. @paodb can you investigate?

**Comment by paodb** [comment]
Hi @javier-godoy, I did some testing but I'm not able to reproduce the issue. I see no console error and the maps are displaying correctly. And the demo doesn't show the issue either.

**Comment by thomasdewaelheyns** [comment]
I forgot to write an update but a day or two after I reported the issue, it was magically solved without changing anything. So with no changes to the Vaadin dependency or the maps addons version in both production and development environments. In development, the same build was still running without restart or anything.

I can only speculate something happened on Google's side of things since the exception was throwing in a javascript library loaded from their content delivery.

As it is currently working as expected I will close this issue. Thanks for taking the time to investigate.
