### ISSUE TITLE
Upgrade lombok to version 1.18.22 in pom.xml for Java 17

### ISSUE THREAD

**Issue by pezi** [FlowingCode/GoogleMapsAddon#71]
to fix this problem
https://stackoverflow.com/questions/66801256/java-lang-illegalaccesserror-class-lombok-javac-apt-lombokprocessor-cannot-acce

**Comment by javier-godoy** [comment]
Thanks for reporting the issue. Since the dependency is `provided`, I understand this only affects the addon compilation (including compiling it in order to run the demo), but it shouldn't affect the released artifact, hence no release is needed.
