### ISSUE TITLE
The Info close button is not visible

### ISSUE THREAD

**Issue by jonasrotilli** [FlowingCode/GoogleMapsAddon#75]
The Info close button is not visible.

If you click where it normally is, it works, but it's transparent.

**Comment by paodb** [comment]
Reproducible in demo https://addonsv14.flowingcode.com/googlemaps/googlemaps.

![image](https://user-images.githubusercontent.com/30666649/182261415-3e949c10-424a-4914-afa4-defce52bfcb2.png)

**Comment by paodb** [comment]
The fix has been released in version [1.8.1](https://vaadin.com/directory/component/google-maps-addon/1.8.1).
