### ISSUE TITLE
Google map addon is not working in V23.2

### ISSUE THREAD

**Issue by jcgueriaud1** [FlowingCode/GoogleMapsAddon#77]
When I'm trying to use this addon in a sample project in Vaadin 23.2 with Vite.
I have this error:

> Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry

I didn't see a Vaadin 23 branch.

Here is an example: https://github.com/jcgueriaud1/googlemap-v23-issue

**Comment by paodb** [comment]
Hello, there's no Vaadin 23 branch, the latest release of the addon works okay in the latest release of Vaadin (23.1.X).
I was able to reproduce the reported issue, I will try to figure out what breaks the addon in Vaadin 23.2 when using Vite (it works okay if Vite is disabled).

**Comment by Artur-** [comment]
https://github.com/FlowingCode/google-map/pull/22 would partly fix this but then you would need to do the same fix for the dependency https://github.com/johnriv/google-apis (so probably fork it and fix it..)

**Comment by paodb** [comment]
Thanks @Artur- for the contribution and the hint, the web component is now updated with those fixes. @jcgueriaud1 we released a [new version of the addon](https://vaadin.com/directory/component/google-maps-addon/1.8.2). Now it works okay in V23.2.

**Comment by jcgueriaud1** [comment]
It's working perfectly, thanks a lot!
