### ISSUE TITLE
Problem with marker's navigation persistence

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/GoogleMapsAddon#8]
The following was reported in [Vaadin's directory](https://vaadin.com/directory/component/google-maps-addon/discussions):

> Hello , I have following problem: I create map with marker then I navigate to other pages in app and then when I return to the page with map marker disapears.

**Comment by javier-godoy** [comment]
Markers are part of the component state. Based on the description, it seems the component is reinitialized, in which case the map will be reloaded.

**Comment by javier-godoy** [comment]
Closed by #25 per discussion in Vaadin Directory.
