### ISSUE TITLE
Markers: support optimized option

### ISSUE THREAD

**Issue by paodb** [FlowingCode/GoogleMapsAddon#81]
It was decided on https://github.com/FlowingCode/GoogleMapsAddon/issues/43#issuecomment-1074471908 to remove the option as it doesn't exists in the web component part and it does nothing when enabled.

**Comment by javier-godoy** [comment]
Even when this method does nothing, **it's part of the public API**. It should be deprecated with a comment mentioning that the method serves no purpose.

**Comment by paodb** [comment]
Maybe we need to re-think this. The idea of removing (now deprecating) the optimized option was because the web component side doesn't have that property, there for, does nothing if the property is set on the server side addon; but it could be added to the web component, as explained [here](https://developers.google.com/maps/documentation/javascript/markers#optimize). Would that be a better approach?

**Comment by paodb** [comment]
As discussed in 2023-01-16 daily, the optimized property should be added to the web-component part. Then server side addon should be updated to use that new property.

**Comment by paodb** [comment]
Back to To Do as no update was done yet on related web-component [ticket](https://github.com/FlowingCode/google-map/issues/25).
