### ISSUE TITLE
setTilt and setHeading

### ISSUE THREAD

**Issue by jonasrotilli** [FlowingCode/GoogleMapsAddon#90]
This library is very good.
Would it be possible to use the setTilt and setHeading function to rotate the map?

https://developers.google.com/maps/documentation/javascript/examples/webgl/webgl-tilt-rotation

I thought about accessing the map via javascript, but I'm not getting it, if anyone has any ideas.

**Comment by paodb** [comment]
Hello, I was investigating and those properties need to be added to the [web-component part](https://github.com/FlowingCode/google-map) of this component and then we can update the Java API to take them in consideration. We added this task to our immediate backlog and we'll start working on this ASAP.
