### ISSUE TITLE
Prevent Google Maps V3 loading Roboto font

### ISSUE THREAD

**Issue by sanel** [FlowingCode/GoogleMapsAddon#91]
Hi,

I've noticed that, after map was shown, application font would be changed (this includes complete Vaadin view where map is shown). The cause looks like is due to Google Maps API loading Roboto font automatically as explained here [1].

For me, the fix was applying [2] js hack. Maybe there is a better way to handle this from addon or addong could call [2] automatically.

[1] https://stackoverflow.com/questions/25523806/google-maps-v3-prevent-api-from-loading-roboto-font
[2] https://stackoverflow.com/a/74852333

**Comment by sanel** [comment]
The same problem can be visible in demo [1]:

 1. page is loaded with normal fonts
 2. after map is shown, all fonts are now bold (Roboto font)

[1] https://addonsv24.flowingcode.com/googlemaps/googlemaps

**Comment by sanel** [comment]
The same problem is on Linux (Slackware 15) with chrome-ungoogled 113 and latest firefox dev edition.

**Comment by paodb** [comment]
Fix included in new released version [1.8.3](https://github.com/FlowingCode/GoogleMapsAddon/releases/tag/google-maps-1.8.3).

**Comment by sanel** [comment]
thanks!
