### ISSUE TITLE
Get coordinate bounds.

### ISSUE THREAD

**Issue by n-tdi** [FlowingCode/GoogleMapsAddon#93]
Hey! Love the addon, super helpful for Vaadin 14 usage. I was wondering if it was possible to either listen for the `bounds_changed` event in google's maps api and then, using the `getBounds()` function, return the two coordinate bounds. I want to implement a functionality so I can see all the markers that are currently visible into my app. Is this possible to get added or is there some javascript events I can listen to?

I was doing some poking around inside of the source and was only able to listen to drag events, not much success.

**Comment by n-tdi** [comment]
Hey! Thanks for the response, when i meant all in view, i mean all the markets currently visible to the user based on their viewport, not having all the markers in view.

**Comment by n-tdi** [comment]
Another possibility:

- Get top-left longlat and the bottom right longlat, 
- With these I could properly check if the targeted marker is in frame

**Comment by paodb** [comment]
@n-tdi I did some investigation and found that you could call getBounds and get the "bounds" coordinates doing something like this:

```java
 googlemap.getElement().executeJs("return this.map.getBounds().toJSON()").then(JsonObject.class, result -> {
        
        // you could get the json string with the coordinates
        String jsonString = result.toJson();
        
        // or you could get each coordinate
        double south = result.get("south").asNumber();
        double north = result.get("north").asNumber();
        double west = result.get("west").asNumber();
        double east = result.get("east").asNumber();
        
        // and then you could add your logic
});
```

**Comment by n-tdi** [comment]
Thanks for the reply @paodb ! I ended up rewriting and implementing google maps into my project without the addon.
