### ISSUE TITLE
No Google Maps API Key or Client ID specified

### ISSUE THREAD

**Issue by jstorch** [FlowingCode/GoogleMapsAddon#95]
When we checkout out our project to a clean directory, build and deploy, we are getting:
“**This page can't load Google Maps correctly**.
Do you own this website?”, error over the map.

Looking in the console, there is a message “No Google Maps API Key or Client ID specified.” Error.
During the build process of the project, there is a warning:
`?babel-target=es5 473:11-16`
`"export 'default' (imported as 'equal') was not found in 'fast-deep-equal'  @ ../node_modules/@flowingcode/google-map/google-map.js?babel-target=es5`

This had all worked before.  We didn't make any changes to the mapping code.

Don't know but this could be related to the same problem Vaadin had with bable package here:
[vaadin/flow#16905](https://github.com/vaadin/flow/issues/16905)

The `@babel/plugin-proposal-object-rest-spread` was `renamed to plugin-transform-object-rest-spread`
which required them to rev from 14.8.0 to 14.10.1

In any case, it appears the API Key is not being sent.  google-maps version: 1.8.3

**Comment by paodb** [comment]
Hi @jstorch, in order to try to reproduce the issue, can you share what vaadin version you are using?

**Comment by paodb** [comment]
Closing as stale. Feel free to re-open the issue if still valid.
